create table android_metadata (locale text default 'en_US');

create table Pokemon(
pokemon_number decimal(3,0),
pokemon_name varchar(50) primary key,
species varchar(50));

create table Characteristics(
pokemon_name varchar(50) primary key,
type_1 varchar(50),
type_2 varchar(50));

create table Moves(
move_name varchar(50),
type_1 varchar(50),
status varchar(50),
power_damage decimal(4,0),
accuracy decimal(4,0),
pp decimal(4,0),
effect varchar(250));

create table Team(
team_name varchar(50) primary key);

create table Base_Stats(
pokemon_name varchar(50) primary key,
hp decimal(3,0),
attack decimal(3,0),
defense decimal(3,0),
special_attack decimal(3,0),
special_defense decimal(3,0),
speed decimal(3,0));

create table Items(
item_name varchar(50) primary key,
effect varchar(250));


--

insert into Pokemon values(1, 'Bulbasaur', 'Seed');
insert into Pokemon values(2, 'Ivysaur', 'Seed');
insert into Pokemon values(3, 'Venusaur', 'Seed');
insert into Pokemon values(4, 'Charmander', 'Lizard');
insert into Pokemon values(5, 'Charmeleon', 'Flame');
insert into Pokemon values(6, 'Charizard', 'Flame');
insert into Pokemon values(7, 'Squirtle', 'Tiny Turtle');
insert into Pokemon values(8, 'Wartortle', 'Turtle');
insert into Pokemon values(9, 'Blastoise', 'Shellfish');
insert into Pokemon values(10, 'Caterpie', 'Worm');
insert into Pokemon values(11, 'Metapod', 'Cocoon');
insert into Pokemon values(12, 'Butterfree', 'Butterfly');
insert into Pokemon values(13, 'Weedle', 'Hairy Bug');
insert into Pokemon values(14, 'Kakuna', 'Cocoon');
insert into Pokemon values(15, 'Beedrill', 'Poison Bee');
insert into Pokemon values(16, 'Pidgey', 'Tiny Bird');
insert into Pokemon values(17, 'Pidgeotto', 'Bird');
insert into Pokemon values(18, 'Pidgeot', 'Bird');
insert into Pokemon values(19, 'Rattata', 'Mouse');
insert into Pokemon values(20, 'Raticate', 'Mouse');
insert into Pokemon values(21, 'Spearow', 'Tiny Bird');
insert into Pokemon values(22, 'Fearow', 'Beak');
insert into Pokemon values(23, 'Ekans', 'Snake');
insert into Pokemon values(24, 'Arbok', 'Cobra');
insert into Pokemon values(25, 'Pikachu', 'Mouse');
insert into Pokemon values(26, 'Raichu', 'Mouse');
insert into Pokemon values(27, 'Sandshrew', 'Mouse');
insert into Pokemon values(28, 'Sandslash', 'Mouse');
insert into Pokemon values(29, 'Nidoran(female)', 'Poison Pin');
insert into Pokemon values(30, 'Nidorina', 'Poison Pin');
insert into Pokemon values(31, 'Nidoqueen', 'Drill');
insert into Pokemon values(32, 'Nidoran(male)', 'Poison Pin');
insert into Pokemon values(33, 'Nidorino', 'Poison Pin');
insert into Pokemon values(34, 'Nidoking', 'Drill');
insert into Pokemon values(35, 'Clefairy', 'Fairy');
insert into Pokemon values(36, 'Clefable', 'Fairy');
insert into Pokemon values(37, 'Vulpix', 'Fox');
insert into Pokemon values(38, 'Ninetales', 'Fox');
insert into Pokemon values(39, 'Jigglypuff', 'Balloon');
insert into Pokemon values(40, 'Wigglytuff', 'Balloon');
insert into Pokemon values(41, 'Zubat', 'Bat');
insert into Pokemon values(42, 'Golbat', 'Bat');
insert into Pokemon values(43, 'Oddish', 'Weed');
insert into Pokemon values(44, 'Gloom', 'Weed');
insert into Pokemon values(45, 'Vileplume', 'Flower');
insert into Pokemon values(46, 'Paras', 'Mushroom');
insert into Pokemon values(47, 'Parasect', 'Mushroom');
insert into Pokemon values(48, 'Venonat', 'Insect');
insert into Pokemon values(49, 'Venomoth', 'Poison Moth');
insert into Pokemon values(50, 'Diglett', 'Mole');
insert into Pokemon values(51, 'Dugtrio', 'Mole');
insert into Pokemon values(52, 'Moewth', 'Scratch Cat');
insert into Pokemon values(53, 'Persian', 'Classy Cat');
insert into Pokemon values(54, 'Psyduck', 'Duck');
insert into Pokemon values(55, 'Goldluck', 'Duck');
insert into Pokemon values(56, 'Mankey', 'Pig Monkey');
insert into Pokemon values(57, 'Primeape', 'Pig Monkey');
insert into Pokemon values(58, 'Growlithe', 'Puppy');
insert into Pokemon values(59, 'Arcanine', 'Legendary');
insert into Pokemon values(60, 'Poliwag', 'Tadpole');
insert into Pokemon values(61, 'Poliwhirl', 'Tadpole');
insert into Pokemon values(62, 'Poliwrath', 'Tadpole');
insert into Pokemon values(63, 'Abra', 'Psi');
insert into Pokemon values(64, 'Kadabra', 'Psi');
insert into Pokemon values(65, 'Alakazam', 'Psi');
insert into Pokemon values(66, 'Machop', 'Superpower');
insert into Pokemon values(67, 'Machoke', 'Superpower');
insert into Pokemon values(68, 'Machamp', 'Superpower');
insert into Pokemon values(69, 'Bellsprout', 'Flower');
insert into Pokemon values(70, 'Weepinbell', 'Flycatcher');
insert into Pokemon values(71, 'Victreebel', 'Flycatcher');
insert into Pokemon values(72, 'Tentacool', 'Jellyfish');
insert into Pokemon values(73, 'Tentacruel', 'Jellyfish');
insert into Pokemon values(74, 'Geodude', 'Rock');
insert into Pokemon values(75, 'Graveler', 'Rock');
insert into Pokemon values(76, 'Golem', 'Megaton');
insert into Pokemon values(77, 'Ponyta', 'Fire Horse');
insert into Pokemon values(78, 'Rapidash', 'Fire Horse');
insert into Pokemon values(79, 'Slowpoke', 'Dopey');
insert into Pokemon values(80, 'Slowbro', 'Hermit Crab');
insert into Pokemon values(81, 'Magnemite', 'Magnet');
insert into Pokemon values(82, 'Magneton', 'Magnet');
insert into Pokemon values(83, 'Farfetch`d', 'Wild Duck');
insert into Pokemon values(84, 'Doduo', 'Twin Bird');
insert into Pokemon values(85, 'Dodrio', 'Triple Bird');
insert into Pokemon values(86, 'Seel', 'Sea Lion');
insert into Pokemon values(87, 'Dewgong', 'Sea Lion');
insert into Pokemon values(88, 'Grimer', 'Sludge');
insert into Pokemon values(89, 'Muk', 'Sludge');
insert into Pokemon values(90, 'Shellder', 'Bivalve');
insert into Pokemon values(91, 'Cloyster', 'Bivalve');
insert into Pokemon values(92, 'Gastly', 'Gas');
insert into Pokemon values(93, 'Haunter', 'Gas');
insert into Pokemon values(94, 'Gengar', 'Shadow');
insert into Pokemon values(95, 'Onix', 'Rock Snake');
insert into Pokemon values(96, 'Drowzee', 'Hypnosis');
insert into Pokemon values(97, 'Hypno', 'Hypnosis');
insert into Pokemon values(98, 'Krabby', 'River Crab');
insert into Pokemon values(99, 'Kingler', 'Pincer');
insert into Pokemon values(100, 'Voltorb', 'Ball');
insert into Pokemon values(101, 'Electrode', 'Ball');
insert into Pokemon values(102, 'Exeggcute', 'Egg');
insert into Pokemon values(103, 'Exeggutor', 'Coconut');
insert into Pokemon values(104, 'Cubone', 'Lonely');
insert into Pokemon values(105, 'Marowak', 'Bone Keeper');
insert into Pokemon values(106, 'Hitmonlee', 'Kicking');
insert into Pokemon values(107, 'Hitmonchan', 'Punching');
insert into Pokemon values(108, 'Lickitung', 'Licking');
insert into Pokemon values(109, 'Koffing', 'Poison Gas');
insert into Pokemon values(110, 'Weezing', 'Poison Gas');
insert into Pokemon values(111, 'Rhyhorn', 'Spikes');
insert into Pokemon values(112, 'Rhydon', 'Drill');
insert into Pokemon values(113, 'Chansey', 'Egg');
insert into Pokemon values(114, 'Tangela', 'Vine');
insert into Pokemon values(115, 'Kangaskhan', 'Parent');
insert into Pokemon values(116, 'Horsea', 'Dragon');
insert into Pokemon values(117, 'Seadra', 'Dragon');
insert into Pokemon values(118, 'Goldeen', 'Goldfish');
insert into Pokemon values(119, 'Seaking', 'Goldfish');
insert into Pokemon values(120, 'Staryu', 'Star Shape');
insert into Pokemon values(121, 'Starmie', 'Mysterious');
insert into Pokemon values(122, 'Mr.Mime', 'Barrier');
insert into Pokemon values(123, 'Scyther', 'Mantis');
insert into Pokemon values(124, 'Jynx', 'Human Shape');
insert into Pokemon values(125, 'Electabuzz', 'Electric');
insert into Pokemon values(126, 'Magmar', 'Spitfire');
insert into Pokemon values(127, 'Pinsir', 'Stag Beetle');
insert into Pokemon values(128, 'Tauros', 'Wild Bull');
insert into Pokemon values(129, 'Magikarp', 'Fish');
insert into Pokemon values(130, 'Gyarados', 'Atrocious');
insert into Pokemon values(131, 'Lapras', 'Transport');
insert into Pokemon values(132, 'Ditto', 'Transform');
insert into Pokemon values(133, 'Eevee', 'Evolution');
insert into Pokemon values(134, 'Vaporeon', 'Bubble Jet');
insert into Pokemon values(135, 'Jolteon', 'Lightning');
insert into Pokemon values(136, 'Flareon', 'Flame');
insert into Pokemon values(137, 'Porygon', 'Virtual');
insert into Pokemon values(138, 'Omanyte', 'Spiral');
insert into Pokemon values(139, 'Omastar', 'Spiral');
insert into Pokemon values(140, 'Kabuto', 'Shellfish');
insert into Pokemon values(141, 'Kabutops', 'Shellfish');
insert into Pokemon values(142, 'Aerodactyl', 'Fossil');
insert into Pokemon values(143, 'Snorlax', 'Sleeping');
insert into Pokemon values(144, 'Articuno', 'Freeze');
insert into Pokemon values(145, 'Zapdos', 'Electric');
insert into Pokemon values(146, 'Moltres', 'Flame');
insert into Pokemon values(147, 'Dratini', 'Dragon');
insert into Pokemon values(148, 'Dragonair', 'Dragon');
insert into Pokemon values(149, 'Dragonite', 'Dragon');
insert into Pokemon values(150, 'Mewtwo', 'Genetic');
insert into Pokemon values(151, 'Mew', 'New Species');

--

insert into Characteristics values('Bulbasaur','Grass','Poison');
insert into Characteristics values('Ivysaur','Grass','Poison');
insert into Characteristics values('Venusaur','Grass','Poison');
insert into Characteristics values('Charmander','Fire',null);
insert into Characteristics values('Charmeleon','Fire',null);
insert into Characteristics values('Charizard','Fire','Flying');
insert into Characteristics values('Squirtle','Water',null);
insert into Characteristics values('Wartortle','Water',null);
insert into Characteristics values('Blastoise','Water',null);
insert into Characteristics values('Caterpie','Bug',null);
insert into Characteristics values('Metapod','Bug',null);
insert into Characteristics values('Butterfree','Bug','Flying');
insert into Characteristics values('Weedle','Bug','Poison');
insert into Characteristics values('Kakuna','Bug','Poison');
insert into Characteristics values('Beedrill','Bug','Poison');
insert into Characteristics values('Pidgey','Normal','Flying');
insert into Characteristics values('Pidgeotto','Normal','Flying');
insert into Characteristics values('Pidgeot','Normal','Flying');
insert into Characteristics values('Rattata','Normal',null);
insert into Characteristics values('Raticate','Normal',null);
insert into Characteristics values('Spearow','Normal',null);
insert into Characteristics values('Fearow','Normal','Flying');
insert into Characteristics values('Ekans','Poison',null);
insert into Characteristics values('Arbok','Poison',null);
insert into Characteristics values('Pikachu','Electric',null);
insert into Characteristics values('Raichu','Electric',null);
insert into Characteristics values('Sandshrew','Ground',null);
insert into Characteristics values('Sandslash','Ground',null);
insert into Characteristics values('Nidoran(female)','Poison',null);
insert into Characteristics values('Nidorina','Poison',null);
insert into Characteristics values('Nidoqueen','Poison','Ground');
insert into Characteristics values('Nidoran(male)','Poison',null);
insert into Characteristics values('Nidorio','Poison',null);
insert into Characteristics values('Nidoking','Poison','Ground');
insert into Characteristics values('Clefairy','Fairy',null);
insert into Characteristics values('Clefable','Fairy',null);
insert into Characteristics values('Vulpix','Fire',null);
insert into Characteristics values('Ninetales','Fire',null);
insert into Characteristics values('Pigglypuff','Fairy','Normal');
insert into Characteristics values('Wigglytuff','Fairy','Normal');
insert into Characteristics values('Zubat','Poison','Flying');
insert into Characteristics values('Golbat','Poison','Flying');
insert into Characteristics values('Oddish','Grass','Poison');
insert into Characteristics values('Vileplume','Grass','Poison');
insert into Characteristics values('Paras','Bug','Grass');
insert into Characteristics values('Parasect','Bug','Grass');
insert into Characteristics values('Venonat','Bug','Poison');
insert into Characteristics values('Venomoth','Bug','Poison');
insert into Characteristics values('Diglett','Ground',null);
insert into Characteristics values('Dugtrio','Ground',null);
insert into Characteristics values('Meowth','Normal',null);
insert into Characteristics values('Persian','Normal',null);
insert into Characteristics values('Psyduck','Waer',null);
insert into Characteristics values('Golduck','Water',null);
insert into Characteristics values('Mankey','Fighting',null);
insert into Characteristics values('Primeape','Fighting',null);
insert into Characteristics values('Growlithe','Fire',null);
insert into Characteristics values('Arcanine','Fire',null);
insert into Characteristics values('Poliwag','Water',null);
insert into Characteristics values('Poliwhirl','Water',null);
insert into Characteristics values('Poliwrath','Water','Fighting');
insert into Characteristics values('Abra','Psychic',null);
insert into Characteristics values('Kadabra','Psychic',null);
insert into Characteristics values('Alakazam','Psychic',null);
insert into Characteristics values('Machop','Fighting',null);
insert into Characteristics values('Machoke','Fighting',null);
insert into Characteristics values('Machamp','Fighting','null');
insert into Characteristics values('Bellsprout','Grass','Poison');
insert into Characteristics values('Weepinbell','Grass','Poison');
insert into Characteristics values('Victreebel','Grass','Poison');
insert into Characteristics values('Tentacool','Water','Poison');
insert into Characteristics values('Tentacuel','Water','Poison');
insert into Characteristics values('Geodude','Rock','Ground');
insert into Characteristics values('Graveler','Rock','Ground');
insert into Characteristics values('Golem','Rock','Ground');
insert into Characteristics values('Ponyta','Fire',null);
insert into Characteristics values('Rapidash','Fire',null);
insert into Characteristics values('Slowpoke','Water','Psychic');
insert into Characteristics values('Slowbro','Water','Psychic');
insert into Characteristics values('Magnemite','Electric','Steel');
insert into Characteristics values('Magneton','Electric','Steel');
insert into Characteristics values('Farfetch`d','Normal','Flying');
insert into Characteristics values('Duduo','Normal','Flying');
insert into Characteristics values('Dodrio','Normal','Flying');
insert into Characteristics values('Seel','Water',null);
insert into Characteristics values('Dewgong','Water','Ice');
insert into Characteristics values('Grimer','Poison',null);
insert into Characteristics values('Muk','Poison',null);
insert into Characteristics values('Shellder','Water',null);
insert into Characteristics values('Cloyster','Water','Ice');
insert into Characteristics values('Gastly','Ghost','Poison');
insert into Characteristics values('Haunter','Ghost','Poison');
insert into Characteristics values('Gengar','Ghost','Poison');
insert into Characteristics values('Onix','Rock','Ground');
insert into Characteristics values('Drowzee','Psychic',null);
insert into Characteristics values('Hypno','Psychic',null);
insert into Characteristics values('Krabby','Water',null);
insert into Characteristics values('Kingler','Water',null);
insert into Characteristics values('Voltorb','Electric',null);
insert into Characteristics values('Electrode','Electric',null);
insert into Characteristics values('Exeggcute','Grass','Psychic');
insert into Characteristics values('Exeggutor','Grass','Psychic');
insert into Characteristics values('Cubone','Ground',null);
insert into Characteristics values('Marowak','Ground',null);
insert into Characteristics values('Hitmonlee','Fighting',null);
insert into Characteristics values('Hitmonchan','Fighting',null);
insert into Characteristics values('Lickitung','Normal',null);
insert into Characteristics values('Koffing','Poison',null);
insert into Characteristics values('Weezing','Poison',null);
insert into Characteristics values('Rhyhorn','Ground','Rock');
insert into Characteristics values('Rhydon','Ground','Rock');
insert into Characteristics values('Chansey','Normal',null);
insert into Characteristics values('Tangela','Grass',null);
insert into Characteristics values('Kangaskhan','Normal',null);
insert into Characteristics values('Horsea','Water',null);
insert into Characteristics values('Seadra','Water',null);
insert into Characteristics values('Goldeen','Water',null);
insert into Characteristics values('Seaking','Water',null);
insert into Characteristics values('Staryu','Water',null);
insert into Characteristics values('Starmie','Water','Psychic');
insert into Characteristics values('Mr.Mime','Psychic','Fairy');
insert into Characteristics values('Scyther','Bug','Flying');
insert into Characteristics values('Jynx','Ice','Psychic');
insert into Characteristics values('Electabuzz','Electric',null);
insert into Characteristics values('Magmar','Fire',null);
insert into Characteristics values('Pinsir','Bug',null);
insert into Characteristics values('Tauros','Normal',null);
insert into Characteristics values('Magikarp','Water',null);
insert into Characteristics values('Gyarados','Water','Flying');
insert into Characteristics values('Laptas','Water','Ice');
insert into Characteristics values('Ditto','Normal',null);
insert into Characteristics values('Eevee','Normal',null);
insert into Characteristics values('Vaporeon','Water',null);
insert into Characteristics values('Jolteon','Electric',null);
insert into Characteristics values('Flareon','Fire',null);
insert into Characteristics values('Porygon','Normal',null);
insert into Characteristics values('Omanyte','Rock','Water');
insert into Characteristics values('Omastar','Rock','Water');
insert into Characteristics values('Kabuto','Rock','Water');
insert into Characteristics values('Kabutops','Rock','Water');
insert into Characteristics values('Aerodactyl','Rock','Flying');
insert into Characteristics values('Snorlax','Normal',null);
insert into Characteristics values('Articuno','Ice','Flying');
insert into Characteristics values('Zapdos','Electric','Flying');
insert into Characteristics values('Moltres','Fire','Flying');
insert into Characteristics values('Dratini','Dragon',null);
insert into Characteristics values('Dragonair','Dragon',null);
insert into Characteristics values('Dragonite','Dragon','Flying');
insert into Characteristics values('Mewtwo','Psychic',null);
insert into Characteristics values('Mew','Psychic',null);

--

insert into Base_Stats values('Bulbasaur',45,49,49,65,65,45);
insert into Base_Stats values('Ivysaur',60,62,63,80,80,60);
insert into Base_Stats values('Venusaur',80,100,123,122,120,80);
insert into Base_Stats values('Charmander',39,52,43,60,50,65);
insert into Base_Stats values('Charmeleon',58,64,58,80,65,80);
insert into Base_Stats values('Charizard',78,84,78,109,85,100);
insert into Base_Stats values('Squirtle',44,48,65,50,64,43);
insert into Base_Stats values('Wartortle',59,63,80,65,80,58);
insert into Base_Stats values('Blastoise',79,83,100,85,105,78);
insert into Base_Stats values('Caterpie',45,30,35,20,20,45);
insert into Base_Stats values('Metapod',50,20,55,25,25,30);
insert into Base_Stats values('Butterfree',60,45,50,90,80,70);
insert into Base_Stats values('Weedle',40,35,30,20,20,50);
insert into Base_Stats values('Kakuna',45,25,50,25,25,35);
insert into Base_Stats values('Beedrill',65,90,40,45,80,75);
insert into Base_Stats values('Pidgey',40,45,40,35,35,56);
insert into Base_Stats values('Pidgeottto',63,60,55,50,50,71);
insert into Base_Stats values('Pidgeot',83,80,75,70,70,101);
insert into Base_Stats values('Rattata',30,56,35,26,35,72);
insert into Base_Stats values('Raticate',55,81,60,50,70,97);
insert into Base_Stats values('Spearow',40,60,30,31,31,70);
insert into Base_Stats values('Fearow',65,90,65,61,61,100);
insert into Base_Stats values('Ekans',35,90,44,40,54,55);
insert into Base_Stats values('Arbok',60,95,69,65,79,80);
insert into Base_Stats values('Pikachu',35,55,40,50,50,90);
insert into Base_Stats values('Raichu',60,90,55,90,80,110);
insert into Base_Stats values('Sandshrew',50,75,85,20,30,40);
insert into Base_Stats values('Sandslash',50,75,85,20,30,40);
insert into Base_Stats values('Nidoran(female)',55,47,52,40,40,41);
insert into Base_Stats values('Nidorina',70,62,67,55,55,56);
insert into Base_Stats values('Nidoqueen',90,92,87,75,85,76);
insert into Base_Stats values('Nidoran(male)',46,57,42,40,40,50);
insert into Base_Stats values('Nidorino',61,72,57,55,55,65);
insert into Base_Stats values('Nidoking',81,102,77,85,75,85);
insert into Base_Stats values('Clefairy',70,45,48,60,65,35);
insert into Base_Stats values('Clefable',95,70,73,95,90,60);
insert into Base_Stats values('Vulpix',38,41,40,50,65,65);
insert into Base_Stats values('Ninetales',73,76,75,81,100,100);
insert into Base_Stats values('Jigglypuff',115,45,20,45,25,20);
insert into Base_Stats values('Wigglytuff',140,70,45,85,50,45);
insert into Base_Stats values('Zubat',40,45,35,30,40,55);
insert into Base_Stats values('Golbat',75,80,70,65,75,90);
insert into Base_Stats values('Oddish',45,50,55,75,65,30);
insert into Base_Stats values('Gloom',60,65,70,85,75,40);
insert into Base_Stats values('Vileplume',75,80,85,110,90,50);
insert into Base_Stats values('Paras',35,70,55,45,55,25);
insert into Base_Stats values('Parasect',60,95,80,60,80,30);
insert into Base_Stats values('Venonat',60,55,50,40,55,45);
insert into Base_Stats values('Venomoth',70,65,60,90,75,90);
insert into Base_Stats values('Diglett',10,55,25,35,45,95);
insert into Base_Stats values('Dugtrio',35,100,50,50,70,120);
insert into Base_Stats values('Meowth',40,45,35,40,40,90);
insert into Base_Stats values('Persian',65,70,60,65,65,115);
insert into Base_Stats values('Psyduck',50,52,48,65,50,55);
insert into Base_Stats values('Golduck',80,82,78,95,80,85);
insert into Base_Stats values('Mankey',40,80,35,35,45,70);
insert into Base_Stats values('Primeape',65,105,60,60,70,95);
insert into Base_Stats values('Growlithe',55,70,45,70,50,60);
insert into Base_Stats values('Arcanine',90,110,80,100,80,95);
insert into Base_Stats values('Poliwag',40,50,40,40,40,90);
insert into Base_Stats values('Poliwrath',90,95,95,70,90,70);
insert into Base_Stats values('Abra',25,20,15,105,55,90);
insert into Base_Stats values('Kadabra',40,35,30,120,70,105);
insert into Base_Stats values('Alakazam',55,50,45,135,95,120);
insert into Base_Stats values('Machop',70,80,50,35,35,35);
insert into Base_Stats values('Machoke',80,100,70,50,60,45);
insert into Base_Stats values('Machamp',90,130,80,65,85,55);
insert into Base_Stats values('Bellsprout',50,75,35,70,30,40);
insert into Base_Stats values('Weepinbell',65,90,50,85,45,55);
insert into Base_Stats values('Victreebel',80,105,65,100,70,70);
insert into Base_Stats values('Tentacool',40,40,35,50,100,70);
insert into Base_Stats values('Tentacruel',80,70,65,80,120,100);
insert into Base_Stats values('Geodude',40,80,100,30,30,20);
insert into Base_Stats values('Graveler',55,95,115,45,45,35);
insert into Base_Stats values('Golem',80,120,130,55,65,45);
insert into Base_Stats values('Ponyta',50,85,55,65,65,90);
insert into Base_Stats values('Rapidash',65,100,70,80,80,105);
insert into Base_Stats values('Slowpoke',90,65,65,40,40,15);
insert into Base_Stats values('Slowbro',95,75,110,100,80,30);
insert into Base_Stats values('Magnemite',25,35,70,95,55,45);
insert into Base_Stats values('Magneton',50,60,95,120,70,70);
insert into Base_Stats values('Farfetch`d',52,90,55,58,62,60);
insert into Base_Stats values('Duduo',35,85,45,35,35,75);
insert into Base_Stats values('Dudrio',60,110,70,60,60,110);
insert into Base_Stats values('Seel',65,45,55,45,70,45);
insert into Base_Stats values('Dewgong',90,70,80,70,95,70);
insert into Base_Stats values('Grimer',80,80,50,40,50,25);
insert into Base_Stats values('Muk',105,105,75,65,100,50);
insert into Base_Stats values('Shellder',30,65,100,45,25,40);
insert into Base_Stats values('Cloyster',50,95,180,85,45,70);
insert into Base_Stats values('Gastly',30,35,30,100,35,80);
insert into Base_Stats values('Haunter',45,50,45,115,55,95);
insert into Base_Stats values('Gengar',60,65,60,130,75,110);
insert into Base_Stats values('Onix',35,45,160,30,45,70);
insert into Base_Stats values('Drowzee',60,48,45,43,90,42);
insert into Base_Stats values('Hypno',85,73,70,73,115,67);
insert into Base_Stats values('Krabby',30,105,90,25,25,50);
insert into Base_Stats values('Kingler',55,130,115,50,50,75);
insert into Base_Stats values('Voltorb',40,30,50,55,55,100);
insert into Base_Stats values('Electrode',60,50,70,80,80,150);
insert into Base_Stats values('Exeggcute',60,40,80,60,45,40);
insert into Base_Stats values('Exeggutor',95,95,85,125,75,45);
insert into Base_Stats values('Cubone',50,50,95,40,50,35);
insert into Base_Stats values('Marowak',60,80,110,50,80,45);
insert into Base_Stats values('Hitmonlee',50,120,53,35,110,87);
insert into Base_Stats values('Hitmonchan',50,105,79,35,110,76);
insert into Base_Stats values('Lickitung',90,55,75,60,75,30);
insert into Base_Stats values('Koffing',40,65,95,60,45,35);
insert into Base_Stats values('Weezing',65,90,120,85,70,60);
insert into Base_Stats values('Rhyhorn',80,85,95,30,30,25);
insert into Base_Stats values('Rhydon',105,130,120,45,45,40);
insert into Base_Stats values('Chansey',250,5,5,35,105,50);
insert into Base_Stats values('Tangela',65,55,115,100,40,60);
insert into Base_Stats values('Kangaskan',105,95,80,40,80,90);
insert into Base_Stats values('Horsea',30,40,70,70,25,60);
insert into Base_Stats values('Seadra',55,65,95,95,45,85);
insert into Base_Stats values('Goldeen',45,67,60,35,50,63);
insert into Base_Stats values('Seaking',80,92,65,65,80,68);
insert into Base_Stats values('Staryu',30,45,55,70,55,85);
insert into Base_Stats values('Starmie',60,75,85,100,85,115);
insert into Base_Stats values('Mr.Mime',40,45,65,100,120,90);
insert into Base_Stats values('Scyther',70,110,80,55,80,105);
insert into Base_Stats values('Jynx',65,50,35,115,95,95);
insert into Base_Stats values('Electabuzz',65,83,57,95,85,105);
insert into Base_Stats values('Magmar',65,95,57,100,85,93);
insert into Base_Stats values('Pinsir',65,125,100,55,70,85);
insert into Base_Stats values('Tauros',75,100,95,40,70,110);
insert into Base_Stats values('Magikarp',20,10,55,15,20,80);
insert into Base_Stats values('Gyarados',95,125,79,60,100,81);
insert into Base_Stats values('Lapras',130,85,80,85,95,60);
insert into Base_Stats values('Ditto',48,48,48,48,48,48);
insert into Base_Stats values('Eevee',55,55,50,45,65,55);
insert into Base_Stats values('Vaporeon',130,65,60,110,95,65);
insert into Base_Stats values('Jolteon',65,65,160,110,95,130);
insert into Base_Stats values('Flareon',64,130,60,95,110,65);
insert into Base_Stats values('Porygon',65,60,70,85,75,40);
insert into Base_Stats values('Omanyte',35,40,100,90,55,35);
insert into Base_Stats values('Omastar',70,60,125,115,70,55);
insert into Base_Stats values('Kabuto',30,80,90,55,45,55);
insert into Base_Stats values('Kabutops',60,115,105,65,70,80);
insert into Base_Stats values('Aerodactyl',80,105,65,60,75,130);
insert into Base_Stats values('Snorlax',160,110,65,65,110,30);
insert into Base_Stats values('Articuno',90,85,100,95,125,85);
insert into Base_Stats values('Zapdos',90,90,85,125,90,100);
insert into Base_Stats values('Moltres',90,100,90,125,85,90);
insert into Base_Stats values('Dratini',41,64,45,50,50,50);
insert into Base_Stats values('Dragonair',61,84,65,70,70,70);
insert into Base_Stats values('Dragonite',91,134,95,100,100,80);
insert into Base_Stats values('Mewtwo',106,150,70,194,120,140);
insert into Base_Stats values('Mew',100,100,100,100,100,100);

--

insert into Team values('Team Tran');
insert into Team values('Team Pointer');

--

insert into Items values('Master Ball', 'A Ball that captures any wild Pok�mon without fail.');
insert into Items values('Ultra Ball', 'A Ball thrown at wild Pok�mon to catch them.');
insert into Items values('Great Ball', 'A Ball thrown at wild Pok�mon to catch them.');
insert into Items values('Poke Ball', 'A Ball thrown at wild Pok�mon to catch them.');
insert into Items values('Safari Ball', 'A Ball thrown at wild Pok�mon to catch them.');
insert into Items values('Pokedex', 'Gotta catch them all!');
insert into Items values('Town Map', 'Map.');
insert into Items values('Potion', 'Restores HP that have been lost in battle by 20 HP.');
insert into Items values('Super Potion', 'Restores HP that have been lost in battle by 50 HP.');
insert into Items values('Hyper Potion', 'Restores HP that have been lost in battle by 200 HP.');
insert into Items values('Full Restore', 'Fully restores HP and cures all ailments, such as poisoning.');


--

insert into Moves values('Absorb', 'Grass','Special',20,100,25,'User recovers half the HP inflicted on opponent.');
insert into Moves values('Acid','Poison','Special',40,100,30,'May lower opponent`s Special Defense');
insert into Moves values('Agility','Psychic','Status',null,null,30,'Sharply raises user`s Speed');
insert into Moves values('Acid Armor','Poison','Status',null,null,20,'Sharply Raises user`s Defense');
insert into Moves values('Amnesia','Phychic','Status',null,null,20,'Sharply Raises user`s Special Defense');
insert into Moves values('Aurora Beam','Ice','Special',65,100,20,'May lower opponent`s Attack');
insert into Moves values('Barrage','Normal','Physical',15,85,20,'Hits 2-5 times in one turn.');
insert into Moves values('Barrier','Psychic','Status',null,null,20,'Sharply raises user`s Defense');
insert into Moves values('Bide','Normal','Physical',null,null,20,'User takes damage for two turns then strikes back double');
insert into Moves values('Bind','Normal','Physical',null,null,10,'Traps opponent, damaging them for 4-5 turns.');
insert into Moves values('Bite','Dark','Physical',60,100,25,'May cause flinching.');
insert into Moves values('Blizzard','Ice','Special',110,70,5,'May freeze opponent.');
insert into Moves values('Body Slam','Normal','Physical',85,100,15,'May paralyze opponent.');
insert into Moves values('Bone Club','Ground','Physical',65,85,20,'May cause flinching.');
insert into Moves values('Bonemerang','Ground','Physical',50,90,10,'Hits twice in one turn.');
insert into Moves values('Bubble','Water','Special',40,100,30,'May lower opponent`s Speed.');
insert into Moves values('Bubble Beam','Water','Special',65,100,20,'May lower opponent`s Speed.');
insert into Moves values('Clamp','Water','Physical',35,85,10,'Traps opponent, damaging them for 4-5 turns.');
insert into Moves values('Comet Punch','Normal','Physical',18,85,15,'Hits 2-5 times in one turn.');
insert into Moves values('Confuse Ray','Ghost','Status',null,100,10,'Confuses opponent.');
insert into Moves values('Confusion','Psychic','Special',50,100,25,'May confuse opponent.');
insert into Moves values('Constrict','Normal','Physical',10,100,35,'May lower opponent`s Speed by one stage.');
insert into Moves values('Counter','Fighting','Physical',null,100,20,'When hit by a Physical Attack, user strikes back with 2x power.');
insert into Moves values('Crabhammer','Water','Physical',100,90,10,'High critical hit ratio');
insert into Moves values('Cut','Normal','Physical',50,95,30,'Cut');
insert into Moves values('Defense Curl','Normal','Status',null,null,40,'Raises user`s Defense');
insert into Moves values('Dig','Ground','Physical',80,100,10,'Digs underground on first turn, attacks on second. Can also escape from caves.');
insert into Moves values('Disable','Normal','Status',null,100,20,'Opponent can`t use its last attack for a few turns.');
insert into Moves values('Dizzy Punch','Normal','Physical',70,100,10,'Opponent can`t use its last attack for a few turns.');
insert into Moves values('Double Kick','Fighting','Physical',30,100,30,'Hits twice in one turn.');
insert into Moves values('Double Team','Normal','Status',null,null,15,'Raises user`s Evasiveness.');
insert into Moves values('Double-Edge','Normal','Physical',120,100,15,'User receives recoil damage.');
insert into Moves values('Dragon Rage','Dragon','Special',null,100,10,'Always inflicts 40 HP.');
insert into Moves values('Dream Eater','Psychic','Special',100,100,15,'User recovers half of the HP inflicted on a sleeping opponent.');
insert into Moves values('Drill Peck','Flying','Physical',80,100,20,'Pecked');
insert into Moves values('Earthquake','Ground','Physical',100,100,10,'Power is doubled if opponent is underground from using Dig.');
insert into Moves values('Egg Bomb','Normal','Physical',100,75,10,'Egg bombed.');
insert into Moves values('Ember','Fire','Special',40,100,25,'May burn opponent.');
insert into Moves values('Explosion','Normal','Physical',250,100,5,'User faints.');
insert into Moves values('Fire Blast','Fire','Special',110,85,5,'May burn opponent.');
insert into Moves values('Fire punch','Fire','Special',75,100,15,'May burn opponent.');
insert into Moves values('Fire spin','Fire','Special',35,85,15,'Traps opponent, damaging them for 4-5 turns.');
insert into Moves values('Fissure','Ground','Physical',null,null,5,'One-Hit-KO, if it hits.');
insert into Moves values('Flamethrower','Fire','Special',90,100,15,'May burn opponent.');
insert into Moves values('Flash','Normal','null',100,20,20,'Lowers opponent`s Accuracy');
insert into Moves values('Fly','Flying','Physical',90,95,15,'Flies up on first turn, attacks on second turn.');
insert into Moves values('Focus Energy','Normal','Status',null,null,30,'Increases critical hit ratio.');
insert into Moves values('Fury Attack','Normal','Physical',15,85,20,'Hits 2-5 times in one turn.');
insert into Moves values('Fury Swipes','Normal','Physical',18,80,15,'Hits 2-5 times in one turn.');
insert into Moves values('Glare','Normal','Status',null,100,30,'Paralyzes opponent.');
insert into Moves values('Growl','Normal','Status',null,100,40,'Lowers opponent`s Attack.');
insert into Moves values('Growth','Normal','Status',null,null,40,'Raises user`s Attack and Special Attack.');
insert into Moves values('Guillotine','Normal','Physical',null,null,5,'One-HitKO, if it hits.');
insert into Moves values('Gust','Flying','Special',40,100,35,'Hits Pokemon using Fly/Bounce with double power.');
insert into Moves values('Harden','Normal','Status',null,null,30,'Raises user`s Defense.');
insert into Moves values('Haze','Ice','Status',null,null,30,'Resets all stat changes.');
insert into Moves values('Headbutt','Normal','Physical',70,100,15,'May cause flinching.');
insert into Moves values('High Jump Kick','Fighting','Physical',130,90,10,'If it misses, the user loses half their HP.');
insert into Moves values('Horn Attack','Normal','Physical',65,100,25,'Horn attack');
insert into Moves values('Horn Drill','Normal','Physical',null,null,5,'One-Hit-KO, if it hits.');
insert into Moves values('Hydro Pump','Water','Special',110,80,5,'A huge blast of water.');
insert into Moves values('Hyper Beam','Normal','Special',150,90,5,'User must recharge next turn.');
insert into Moves values('Hyper Fang','Normal','Physical',80,90,15,'May cause flinching.');
insert into Moves values('Hypnosis','Psychic','Status',null,60,20,'Puts opponent to sleep.');
insert into Moves values('Ice Beam','Ice','Special',90,100,10,'May freeze opponent.');
insert into Moves values('Ice Punch','Ice','Physical',75,100,15,'May freeze opponent.');
insert into Moves values('Jump Kick','Fighting','Physical',100,95,10,'If it misses, the user loses half their HP.');
insert into Moves values('Karate Chop','Fighting','Physical',50,100,25,'High critical hit ratio.');
insert into Moves values('Kinesis','Psychic','Status',null,80,15,'Lowers opponent`s Accuracy.');
insert into Moves values('Leech Life','Bug','Physical',80,100,10,'User recovers half the HP inflicted on opponent.');
insert into Moves values('Leech Seed','Grass','Status',null,90,10,'User steals HP from opponent each turn.');
insert into Moves values('Leer','Normal','Status',null,100,30,'Lowers opponent`s Defense.');
insert into Moves values('Lick','Ghost','Physical',30,100,30,'May paralyze opponent.');
insert into Moves values('Light Screen','Psychic','Status',null,null,30,'Halves damage from Special attacks from 5 turns.');
insert into Moves values('Lovely Kiss','Normal','Status',null,null,40,'Raises user`s Attack.');
insert into Moves values('Mega Drain','Grass','Special',40,100,15,'User recovers half the HP inflicted on opponent.');
insert into Moves values('Mega Kick','Normal','Physical',120,75,5,'Kicked');
insert into Moves values('Mega Punch','Normal','Physical',80,85,20,'One pUNCHED!');
insert into Moves values('Metronome','Normal','Status',null,null,10,'User performs any move in the game at random.');
insert into Moves values('Mimic','Normal','Status',null,null,10,'Copies the opponent`s last move.');
insert into Moves values('Minimize','Normal','Status',null,null,10,'Sharply raises user`s Evasiveness.');
insert into Moves values('Mirror Move','Flying','Status',null,null,20,'User performs the opponent`s last move.');
insert into Moves values('Mist','Ice','Status',null,null,30,'User`s stats cannot be changed for a period of time.');
insert into Moves values('Night Shade','Ghost','Special',null,100,15,'Inflicts damage equal to user`s level.');
insert into Moves values('Pay Day','Normal','Physical',40,100,20,'A small amount of money is gained after the battle resolves.');
insert into Moves values('Peck','Flying','Physical',35,100,35,'Pecked.');
insert into Moves values('Petal Dance','Grass','Special',120,100,10,'User attacks for 2-3 turns but then becomes confused.');
insert into Moves values('Pin Missile','Bug','Physical',25,95,20,'Hits 2-5 times in one turn.');
insert into Moves values('Poison Gas','Poison','Status',null,90,40,'Poisons opponent.');
insert into Moves values('Poison Powder','Poison','Status',null,75,35,'Poisons opponent.');
insert into Moves values('Poison Sting','Poison','Physical',15,100,35,'May poison the opponent.');
insert into Moves values('Pound','Normal','Physical',40,100,35,'Pounded');
insert into Moves values('Psybeam','Psychic','Special',65,100,20,'May confuse opponent.');
insert into Moves values('Psychic','Psychic','Special',90,100,10,'May lower opponent`s Special Defense.');
insert into Moves values('Psywave','Psychic','Special',null,80,15,'Inflicts damage 50-150% of user`s level.');
insert into Moves values('Quick Attack','Normal','Physical',40,100,30,'User attacks first.');
insert into Moves values('Rage','Normal','Physical',20,100,20,'Raises user`s Attack when hit.');
insert into Moves values('Razor Leaf','Grass','Physical',55,95,25,'High critical hit ratio.');
insert into Moves values('Razor Wind','Normal','Special',80,100,10,'Charges on first turn, attacks on second. High critical hit ratio.');
insert into Moves values('Recover','Normal','Status',null,null,10,'User recovers half of its max HP.');
insert into Moves values('Reflect','Psychic','Status',null,null,20,'Halves damage from Physical attacks for 5 turns.');
insert into Moves values('Rest','Psychic','Status',null,null,10,'User sleeps for 2 turns, but user is fully healed.');
insert into Moves values('Roar','Normal','Status',null,null,20,'In battle, the opponent switches. In the wild, the Pokemon runs.');
insert into Moves values('Rock SLide','Rock','Physical',75,90,10,'May cause flinching.');
insert into Moves values('Rock Throw','Rock','Physical',50,90,15,'Throwing Rocks');
insert into Moves values('Rolling Kick','Fighting','Physical',60,85,15,'May cause flinching.');
insert into Moves values('Sand Attack','Ground','Status',null,100,15,'Lowers opponent`s Accuracy.');
insert into Moves values('Scratch','Normal','Physical',40,100,35,'Ouch.');
insert into Moves values('Screech','Normal','Status',null,85,40,'Sharply lowers opponent`s Defense.');
insert into Moves values('Seismic Toss','Fighting','Physical',null,100,20,'Inflicts damage equal to user`s level.');
insert into Moves values('Self-Destruct','Normal','Physical',200,100,5,'User faints.');
insert into Moves values('Sharpen','Normal','Status',null,null,30,'Raises user`s Attack.');
insert into Moves values('Sing','Normal','Status',null,55,15,'Puts opponent to sleep.');
insert into Moves values('Skull Bash','Normal','Physical',130,100,10,'Raises Defense on first turn, attacks on second.');
insert into Moves values('Sky Attack','Flying','Physical',140,90,5,'Charges on first turn, attacks on second. May cause flinching.');
insert into Moves values('Slam','Normal','Physical',80,75,20,'Slammed.');
insert into Moves values('Slash','Normal','Physical',70,100,20,'High critical hit ratio.');
insert into Moves values('Sleep Powder','Grass','Status',null,75,15,'Puts opponent to sleep.');
insert into Moves values('Sludge','Poison','Special',65,100,20,'May poison opponent.');
insert into Moves values('Smog','Poison','Special',30,70,20,'My poison opponent.');
insert into Moves values('Smokescreen','Normal','Status',null,100,20,'Lowers opponent`s Accuracy.');
insert into Moves values('Soft-Boiled','Normal','Status',null,null,10,'User recovers half its max HP.');
insert into Moves values('Solar Beam','Grass','Special',120,100,10,'Charges on first turn, attacks on second.');
insert into Moves values('Sonic Boom','Normal','Special',null,90,20,'Always inflicts 20 HP.');
insert into Moves values('Spike Cannon','Normal','Physical',20,100,15,'Hits 2-5 times in one turn.');
insert into Moves values('Splash','Normal','Status',null,null,40,'Doesn`t do ANYTHING.');
insert into Moves values('Spore','Grass','Status',null,100,15,'Puts opponent to sleep.');
insert into Moves values('Stomp','Normal','Physical',65,100,20,'May cause flinching.');
insert into Moves values('Strength','Normal','Physical',80,100,15,'Push dat way.');
insert into Moves values('String Shot','Bug','Status',null,95,40,'Sharply lowers opponent`s Speed.');
insert into Moves values('Struggle','Normal','Physical',50,100,null,'Only usable when all PP are gone. Hurts the user.');
insert into Moves values('Stun Spore','Grass','Status',null,75,30,'Paralyzes opponent.');
insert into Moves values('Submission ','Fighting','Physical',80,80,20,'User receives recoil damage.');
insert into Moves values('Substitute','Normal','Status',null,null,10,'Uses HP to creates a decoy that takes hits.');
insert into Moves values('Super Fang','Normal','Physical',null,90,10,'Always takes off half of the opponent`s HP.');
insert into Moves values('Supersonic','Normal','Status',null,55,20,'Confuses opponent.');
insert into Moves values('Surf','Water','Special',90,100,15,'Hits all adjacent Pokemon.');
insert into Moves values('Swift','Normal','Special',60,Infinite,20,'Ignores Accuracy and Evasiveness.');
insert into Moves values('Swords Dance','Normal','Status',null,null,20,'Sharply raises user`s Attack.');
insert into Moves values('Tackle','Normal','Physical',40,100,35,'Tackled');
insert into Moves values('Tail Whip','Normal','Status',null,100,30,'Lowers opponent`s Defense.');
insert into Moves values('Take Down','Normal','Physical ',90,85,20,'User receives recoil damage.');
insert into Moves values('Teleport','Psychic','Status',null,null,20,'Allows user to flee wild battles; also warps player to last PokeCenter.');
insert into Moves values('Thrash','Normal','Physical',120,100,10,'User attacks for 2-3 turns but then becomes confused.');
insert into Moves values('Thunder','Electric','Special',110,70,10,'May paralyze opponent.');
insert into Moves values('Thunder Punch','Electric','Physical',75,100,15,'May paralyze opponent.');
insert into Moves values('Thunder Shock','Electric','Special',40,100,30,'May paralyze opponent.');
insert into Moves values('Thunderbolt','Electric','Special',90,100,15,'May paralyze opponent.');
insert into Moves values('Toxic','Poison','Status',null,90,10,'Badly poisons opponent.');
insert into Moves values('Transform','Normal','Status',null,null,10,'User takes on the form and attacks of the opponent.');
insert into Moves values('Tri Attack','Normal','Special',80,100,10,'May paralyze, burn or freeze opponent.');
insert into Moves values('Twineedle','Bug','Physical',25,100,20,'Hits twice in one turn. May poison opponent.');
insert into Moves values('Vice Grip','Normal','Physical',55,100,30,'No Desc.');
insert into Moves values('Vine Whip','Grass','Physical',45,100,25,'no desc.');
insert into Moves values('Water Gun','Water','Special',40,100,25,'NO desc.');
insert into Moves values('Waterfall','Water','Physical',80,100,15,'May cause flinching.');
insert into Moves values('Whirlwind','Normal','Status',null,null,20,'In battles, the opponent switches. In the wind, the Pokemon runs.');
insert into Moves values('Wing Attack','Flying','Physical',60,100,35,'no desc.');
insert into Moves values('Withdraw','Water','Status',null,null,40,'Raises user`s Defense.');
insert into Moves values('Wrap','Normal','Phyiscal',15,90,20,'Traps opponent, damaging them for 4-5 turns.');






select *
from Base_stats
natural join pokemon
Order by pokemon_number;


